name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup flutter
      uses: jddeep/Flutter-Runner@1.2.0
      with:
          args: pub get

    - name: build apk
      uses: jddeep/Flutter-Runner@1.2.0
      with:
        args: build apk --release
