name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup flutter
      uses: geowatson/flutter-latest@1.0.1
      with:
          args: pub get

    - name: build apk
      uses: geowatson/flutter-latest@1.0.1
      with:
        args: build apk --release
    
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: build/app/outputs/flutter-apk/*.apk
